### ISSUE TITLE
Version file points to a zip of itself

### ISSUE THREAD

**Issue by Gordon-Dry** [HebaruSan/KerbalChangelog#1]
A version file should point to a url where a newer version can be obtained when released.

**Comment by HebaruSan** [comment]
Not sure exactly what you're referring to, but this version file is correct as far as I can tell. The URL property points to the remote version file, and the DOWNLOAD property points to where the latest version of the mod can be obtained.

https://github.com/HebaruSan/KerbalChangelog/blob/028b0dd237b2aee64e674a73ca9e19973818411d/GameData/KerbalChangelog/KerbalChangelog.version#L3-L4

**Comment by Gordon-Dry** [comment]
Well, okay. 
Then the devs of all the other mods are doing it wrong by pointing to a url where a newer version of the mod can be obtained than the actual one. Without a paradox.

**Comment by HebaruSan** [comment]
~~You are mistaken, most mod authors **don't** do it that way (CKAN's bot would alert us if they did). If you know of a few aberrant examples, yes, you should report that to them as a bug.~~

(EDIT: The statement about reporting it as a bug was based on my guess that this issue was addressing the URL property, since the issue's incomplete description and subsequent comments had not specified the property. As indicated below, it is not a bug to use the DOWNLOAD property to link to either a list of releases or the latest ZIP file directly.)

Here's the version file spec so you can verify it for yourself:

https://github.com/CYBUTEK/KSPAddonVersionChecker/blob/5f0c5e8a1f66cc3cde4d2c4b439f7364748a33da/Documents/KSP-AVC/README.htm#L151-L157

> <ul>
> 					<li><b>URL</b> - Optional<br>
> 						Location of a remote version file for update checking.
> 					</li>
> 					<li><b>DOWNLOAD</b> - Optional<br>
> 						Web address where the latest version can be downloaded.<br>
> 						<i>This is only used from the remote version file.</i>
> 					</li>
> </ul>

**Comment by Gordon-Dry** [comment]
`Web address where the latest version can be downloaded.`

"Where" - it should point to a general url like https://github.com/HebaruSan/KerbalChangelog/releases 
Not to the actual version itself. This is a logical paradox. A loophole.

**Comment by HebaruSan** [comment]
Confirmed in the version file spec that either way is correct:

https://github.com/CYBUTEK/KSPAddonVersionChecker/blob/5f0c5e8a1f66cc3cde4d2c4b439f7364748a33da/Documents/KSP-AVC/README.htm#L133

> If you require an update of an add-on and it has a download location set, you will be given a button which will open up your default browser and take you there.  _**This could link directly to the .zip file**_ or to a page with details on how to update.  Note that you will need to close down KSP, install the updates and then restart KSP for them to work.

Emphasis on: "This could link directly to the .zip file"
